## buildspec.yml
version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: cypress-e2e-tests
      env:
        variables:
          IMAGE: public.ecr.aws/cypress-io/cypress/browsers:node12.14.1-chrome85-ff81


env:
  secrets-manager:
    MY_SECRET_ENV: arn:aws:secretsmanager:us-west-2:202683722068:secret:DEVSANDEEPSECRET-5gh7Ze:ENV

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm cache clean --force
      - npm install
      - npm install cypress@8.6.0 --save-dev
      - echo %CYPRESS_INSTALL_BINARY%
      - echo '########## MY MY_SECRET_ENV *************'
      - echo $WHO $WHAT $MY_SECRET_ENV
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - echo 'npm run test'
