## buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install --force
  pre_build:
    commands:
      - npm install --force
  build:
    commands:
      - npm run test
