## buildspec.yml
version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: cypress-e2e-tests
      env:
        variables:
          IMAGE: public.ecr.aws/cypress-io/cypress/browsers:node12.14.1-chrome85-ff81

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - ls
      - npm cache clean --force
      - npm install
      - wget --quiet https://cdn.cypress.io/desktop/8.6.0/linux-x64/cypress.zip
      - ls
      - set CYPRESS_INSTALL_BINARY=cypress.zip
      - npm install cypress@8.6.0 --save-dev
      - echo %CYPRESS_INSTALL_BINARY%
      - npm ci
      - ls
      - echo %ENV%
  pre_build:
    commands:
       - npm ci
  build:
    commands:
      - node_modules/.bin/cypress run
      - npm run test